### ISSUE TITLE
Pop-up does not close in Google Inbox

### ISSUE THREAD

**Issue by eih** [krv5vignesh/Dictionary-extension#1]
The pop-up opens and closes in web pages but in Google Inbox, once you double click on a word and deselect it, the pop-up remains there even if you click to an empty space. You just can't get rid of it.

But once you select another word, it shows the definition for that new word, moving the pop-up to the new selected word. But that's it, you have to refresh the tab to get rid of the pop up.

Here are some screenshots:

![screen shot 2018-01-27 at 12 25 59](https://user-images.githubusercontent.com/31883301/35471974-3926a398-035e-11e8-83d2-9af18b6f9dfa.png)

![screen shot 2018-01-27 at 12 26 10](https://user-images.githubusercontent.com/31883301/35471975-393fd9da-035e-11e8-883c-ab6b3638d4da.png)

![screen shot 2018-01-27 at 12 32 46](https://user-images.githubusercontent.com/31883301/35471977-3962a7c6-035e-11e8-91f3-7da519e293f2.png)

![screen shot 2018-01-27 at 12 32 54](https://user-images.githubusercontent.com/31883301/35471978-397b60fe-035e-11e8-8c9a-a3a26a924988.png)

**Comment by krv5vignesh** [comment]
Added a close button as a quick workaround while I look into the issue. Please update to Version 1.3

**Comment by eih** [comment]
Thanks, close button works, thanks.

**Comment by SelvarajKaruppusamy** [comment]
Can this issue be closed?

**Comment by krv5vignesh** [comment]
Still, clicking outside the popup should close it. Will keep this open for now.

**Comment by SelvarajKaruppusamy** [comment]
I tried but I am not able to recreate this issue. @eih Please check if the popup still doesn't close correctly on clicking outside in your gmail page.

**Comment by eih** [comment]
@SelvarajKaruppusamy I have checked now, and I can confirm that the pop-up closes once I click anywhere in the Gmail and other websites. Thanks.
