### ISSUE TITLE
Popup conflicts with page elements with higher z-index

### ISSUE THREAD

**Issue by SelvarajKaruppusamy** [krv5vignesh/Dictionary-extension#11]
![screenshot-2018-4-22](https://user-images.githubusercontent.com/12389443/39097058-9a1c912c-4674-11e8-969e-e57776f046cf.png)

Source page: [https://developers.google.com/web/fundamentals/primers/promises](https://developers.google.com/web/fundamentals/primers/promises)

**Comment by jtbrough** [comment]
Individual tweet pages on Twitter is a good example of this:
https://twitter.com/gruber/status/1001263829794344961

![2018-05-29_15-57-44](https://user-images.githubusercontent.com/478187/40687869-3e620928-6359-11e8-9649-ad727f52ea83.jpg)

Firefox's z-index is an integer, with a max value of 2147483647. Perhaps that might be a rational value here?

Dated information, but possibly still relevant:
http://softwareas.com/whats-the-maximum-z-index/
