### ISSUE TITLE
Allow user to change search engine used when clicking "More"

### ISSUE THREAD

**Issue by Aicaya** [krv5vignesh/Dictionary-extension#14]
When clicking on "more" it opens up a Google search page. I'd like to request an option to switch the search engine to DuckDuckGo instead.

**Comment by JobLeonard** [comment]
I came to open the same request. Automatically selecting the default search engine unless overridden would be nice too!

**Comment by krv5vignesh** [comment]
The feature has been added. Go to extension options to change the search engine.
