### ISSUE TITLE
Text changes colors and isn't very readable on dark themes

### ISSUE THREAD

**Issue by vtruong68** [krv5vignesh/Dictionary-extension#19]
On sites like reddit when dark mode is enabled (might be an RES only setting), the definition pop-up is a bit difficult to read. 
Similarly, when using stylish for dark mode type themes, the same thing occurs.

http://prntscr.com/kb6m0y
http://prntscr.com/kb6naj

Anyway to make the colors of the popup independent of the site so that it's always black text for definition?

**Comment by andiPossess** [comment]
Ran into the same problem. I thought the extension was completely broken until I tried a different site. Confusingly, it works properly on Youtube dark theme, but not others.
