### ISSUE TITLE
Popup gets created outside of the view for words closer to the edge 

### ISSUE THREAD

**Issue by SelvarajKaruppusamy** [krv5vignesh/Dictionary-extension#2]
I guess the popup position is relative to the position of the word.

Double-clicking a word at the end of a sentence puts the popup outside of the view. Also, scrollbars are created as a side effect.

![issue](https://user-images.githubusercontent.com/12389443/35524112-889702b2-0546-11e8-8e86-9b32881b00e8.png)

**Comment by z1lk** [comment]
Related: when you click a word in the popup, the new popup's position is necessarily to the right and bottom of the existing one. If you click words in the popups several times, the popup will be positioned off the right edge of the screen.

**Comment by SelvarajKaruppusamy** [comment]
I am assuming the above issues are still and I will spend some time to fix them. I will create a PR once I complete.

@krv5vignesh Please let me know if you are already working on it. So that it will not conflict.

**Comment by SelvarajKaruppusamy** [comment]
Fixed the above issues and created a [PR](https://github.com/krv5vignesh/Dictionary-extension/pull/5)

Let me know if you have any comments

**Comment by krv5vignesh** [comment]
Thank you for your work. I am not able to test it right away but I will test it tomorrow and will merge it if there is no issue.

Thanks again for your work. If you have time please take a look at other issues as well.

**Comment by SelvarajKaruppusamy** [comment]
You are welcome :) I will let you know if I have any updates on other issues. Thanks!

**Comment by SelvarajKaruppusamy** [comment]
@krv5vignesh  I have not done any version update or similar with regard to addon update. Please do if needed. Thanks!

**Comment by krv5vignesh** [comment]
No problem. I have updated the manifest file and published the extension. Thanks to your contribution v1.5 is live now.
