### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by SelvarajKaruppusamy** [krv5vignesh/Dictionary-extension#20]
@krv5vignesh I have read a lot of [reviews](https://addons.mozilla.org/en-US/firefox/addon/english-popup-dictionary/reviews/) _not all_, in the Mozilla addon site, and I am interested to help to make this project an even better one. I feel a lot of other people also would feel the same.

I believe, the below would significantly help to improve this project,
1. Create a roadmap -  to prioritize the new features/improvements better
2. Create a style guide - the code will be neater
3. Create a code of conduct

I can also help with the above. Kindly let know your plans on maintaining this project.

**Comment by krv5vignesh** [comment]
I very much intend to keep this project active. It is just that I am not able to work on this frequently.

Give me a day or two, I will merge the pending PRs and I will look at the reviews to find the most requested features.

This is a hobby of mine. So I don't exactly have the know-how to create a style guide or a code of conduct. It'll be great if you can help with that. Thank you.

**Comment by SelvarajKaruppusamy** [comment]
@krv5vignesh This is quite new for me as well. Firstly I will create a PR with a style guide. You can review and can make subsequent changes that are required.

**Comment by SelvarajKaruppusamy** [comment]
Created issue to track adding [style guide](https://github.com/krv5vignesh/Dictionary-extension/issues/21)
