### ISSUE TITLE
Not working in any of my browsers

### ISSUE THREAD

**Issue by vayulove** [krv5vignesh/Dictionary-extension#27]
I've had this installed and working in several browsers for a long time. recently it has stopped working.  When I double click a word the popup still displays but it says "No definition found".

I have several versions of Firefox installed all with separate profiles and I get the same "No definition found" on every one of them.  Any ideas what could be happening?

**Comment by weird-o** [comment]
I'm having the same problem, so it's not just you. I tried removing and reinstalling the extension, but that didn't help.

**Comment by vayulove** [comment]
Thanks, always nice to know you're not alone. I also did the same uninstall and reinstall.  I even installed it fresh on a Firefox that didn't have it previously installed.  I was thinking maybe the dictionary is kept online somewhere and that it's down or something.

**Comment by krv5vignesh** [comment]
Thanks for bringing this to my notice. Didn't know there was an issue. I'll look at the issue and update here.

**Comment by krv5vignesh** [comment]
The API I was using was Wordnik API. They have recently decided to limit the no. of API calls I can make for free. As of Jan 31st, the no of calls I can make per hour is only 100. IIRC it was 1000 calls/hour. Anyway that is the issue.

I looked for other free APIs I can use, but couldn't find anything better so far. Yandex and Glosbe API were free but the definitions are not that good. So it'll take some time until I find an API. If you know some APIs please suggest.

**Comment by ghost** [comment]
maybe it can fit https://dictionaryapi.com/

**Comment by Clover-Leaves** [comment]
I just installed this (2/10/18) and got the same error. Did a little digging and got it to work by changing the Pop-Up Dictionary Settings to:
http://www.wordreference.com/definition/$$

The key was the addition of /definition/ as shown above

**Comment by vayulove** [comment]
> I just installed this (2/10/18) and got the same error. Did a little digging and got it to work by changing the Pop-Up Dictionary Settings to:
> http://www.wordreference.com/definition/$$
> 
> The key was the addition of /definition/ as shown above

Where did you add that? I don't see anything in the preferences that could be set to that.

**Comment by Clover-Leaves** [comment]
[cid:18857cdd-0bc3-4f33-b0e8-6b425e5c9906]
It's late, so I'll have to keep this short.....
In your browser, click your icon that is shown in the red circle......
Click "Settings" at the bottom of the PopUp.
You should see the menu below....
[cid:2a0e1c17-bcda-4880-a7bd-e55a74f629b9]
Click "Edit"
The following appears.........

[cid:659cd4d4-affa-45d0-b7a5-f2041027bfb7]
This is what I see on my computer....
Change the "/fren/" to "/definition/" as shown below

[cid:e87c91fb-6c12-4ef3-884e-cf2b8ec25853]
Save it and try it out.....
If you get this PopUp.......
[cid:b3834e6e-02d5-4ed4-a6d5-54a39462fe67]
Go here and follow the directions.....
https://sites.google.com/site/helloricky432/home/howtodisablefirefoxmixedcontentblocking
[https://sites.google.com/site/helloricky432/_/rsrc/1487346204669/home/howtodisablefirefoxmixedcontentblocking/Untitled.png]<https://sites.google.com/site/helloricky432/home/howtodisablefirefoxmixedcontentblocking>

How to disable Firefox mixed content blocking - R<https://sites.google.com/site/helloricky432/home/howtodisablefirefoxmixedcontentblocking>
sites.google.com

All should work as expected......it has worked on two of my computers so far......

________________________________

**Comment by krv5vignesh** [comment]
The dictionary should work now. The API issue has been fixed.

**Comment by blwol** [comment]
It's not working for me.  Every word I double-click on, results in a "No definition found".

**Comment by vayulove** [comment]
It worked for me when I checked last night after getting the email that it was fixed.  But this morning it also isn't working for me.

**Comment by krv5vignesh** [comment]
Reopening this issue. I opted for a paid plan and it was working fine. Turns out with increase in number of users the paid plan also runs out after some time.

Will keep this issue open until I figure out a long-term solution.

**Comment by krv5vignesh** [comment]
Reopening this issue. I opted for a paid plan and it was working fine. Turns out with increase in number of users the paid plan also runs out after some time.

Will keep this issue open until I figure out a long-term solution.

**Comment by koynoyno** [comment]
Maybe it will be good to substitute Wordnik for another free API as workaround?

**Comment by krv5vignesh** [comment]
The issue has been fixed. Please update to version 1.8.1.

I will keep this issue open for a while.
