### ISSUE TITLE
No longer giving definitions

### ISSUE THREAD

**Issue by blwol** [krv5vignesh/Dictionary-extension#28]
Every word I double-click on, results in a "No definition found".

**Comment by keybored13** [comment]
Having the same problem here too.

**Comment by jeffyor** [comment]
yeah same issue here, was it working prior to 12 hours ago? I just downloaded it, willing to leave it installed if its likely just a small issue that needs to be resolved like a parsing error or something

**Comment by krv5vignesh** [comment]
Issue #27 re-opened. Marking this issue as duplicate.

**Comment by elpoisterio** [comment]
still not working. Every word shows " no definition found"

**Comment by krv5vignesh** [comment]
I have fixed the issue. Please update to version 1.8.3

Sorry for the frequent issues with the dictionary lately. Thanks for your patience.
