### ISSUE TITLE
It doesn't work on my machine, v1.7.3

### ISSUE THREAD

**Issue by Fazel94** [krv5vignesh/Dictionary-extension#29]
All most all of the time it just shows `No definition found` but sometimes, like one out of twenty times it shows proper answers.
My extension version is 1.7.3 and my firefox version is 65.0.

**Comment by wijnand2** [comment]
Same problem here (on the same version numbers) except that I don't occasionally get a definition, just 'no definition found'.

**Comment by krv5vignesh** [comment]
The issue has been fixed. Please update to version 1.8.1

**Comment by krv5vignesh** [comment]
Duplicate issue. See #27
