### ISSUE TITLE
Dark theme popup changes color while loading definition

### ISSUE THREAD

**Issue by koynoyno** [krv5vignesh/Dictionary-extension#30]
![screenshot_20190222-043240_1](https://user-images.githubusercontent.com/46102189/53213738-2dcf6080-365b-11e9-8514-1e1481112bf9.png)

Looks not so nice. I woud prefer not to see yellow color if I have chosen dark mode. 

ASUS Nexus 7, Android 6.0.1

**Comment by krv5vignesh** [comment]
Thanks for letting me know. The issue has been fixed. Please update to version 1.8.3
