### ISSUE TITLE
New versions of extension has been disabled by Mozilla

### ISSUE THREAD

**Issue by krv5vignesh** [krv5vignesh/Dictionary-extension#32]
The extension has been reverted to an old version. Mozilla has disabled the new versions. I am working on fixing the issue.

**Comment by diegodlh** [comment]
I would really like to have this addon in my Firefox, but I can only install version 1.5.3 through the Firefox Add-on site.
So I downloaded the source, installed dependencies with yarn, zipped the contents of the src directory, and changed the extension of the zip file to .xpi.
By the way, I really think it would be great if you could provide users a .xpi file in the project's website, as a workaround until Mozilla provides the newer version again.
Then I loaded the extension as a temporary extension (I tried to install it as a regular extension, but I couldn't; I'm a real newbie in browser extensions!), but when I requested for the definition of a word, it would show up empty.
I tried debugging it and it looks like the API request to api.wordnik.com is failing with HTTP error 429 "Too many requests". I see the request has an api_key. Could it be that the quota was exceeded?
Thank you for taking the time reading this.

**Comment by Swiftzn** [comment]
Still having an issue stuck searching indefinitly

**Comment by saspelund** [comment]
Any update?

**Comment by krv5vignesh** [comment]
I have fixed the issue and published the latest version - 1.8.8. Apologies for the looong delay.
