### ISSUE TITLE
Can't Access Extension Options in Firefox

### ISSUE THREAD

**Issue by Ultrabenosaurus** [krv5vignesh/Dictionary-extension#33]
I'm running extension version 1.5.3 (from the Firefox add-ons website) in Firefox 78.0.2 (64-bit) on Windows 10 Pro and cannot find a way to access to the options / settings for this extension. 

I actually came here with the intention of opening an issue about adding an option to set the font colour of the double-click pop-up, as I have noticed on websites with dark backgrounds and light text the pop-up is not readable; the pop-up is very pale yellow(?) and the text just blends in, so I have to highlight the text to read it. While poking around the files in the repo I noticed mentions of an options screen with the ability to set dark / light / auto modes for the pop-up which should change the text colour. However, when I then investigated the extension in my browser, I can't find any options or settings for it anywhere. 

Can you please fix the options screen or otherwise add a default text colour to the inline CSS on `p#tooltipDictBox`?

**Comment by krv5vignesh** [comment]
Could you please update to the latest version 1.8.8 and then check again. The latest versions were disabled for a while and reverted to a very old version which did not have the extension options. I have update the extension again now

**Comment by Ultrabenosaurus** [comment]
@krv5vignesh it has now updated and I can access the options. The dark mode is very nice, thank you!
