### ISSUE TITLE
Search results are limited to 5

### ISSUE THREAD

**Issue by SelvarajKaruppusamy** [krv5vignesh/Dictionary-extension#4]
I was going through the code and figured out that only maximum of 5 results is shown in the popup. Instead, can we have a fixed height for the results and add a scroll bar if there are more than 5 results?

**Comment by SelvarajKaruppusamy** [comment]
I guess we can close this issue.  For more than 5 definitions, it would be better to see the results in a different page, by clicking the "More" option.

**Comment by krv5vignesh** [comment]
Yes, that would be better
