### ISSUE TITLE
Attribute "target='_blank'" for "More" and "Search" is missing

### ISSUE THREAD

**Issue by tsoliangwu0130** [krv5vignesh/Dictionary-extension#8]
It seems like the dictionary-extension was intended to have `target='_blank'` attribute for **More/Search** text at the button of the pop-up box, but when clicking these links, they redirect the current page to the result page instead of opening a new tab.

![screen shot 2018-04-10 at 4 27 34 pm](https://user-images.githubusercontent.com/9169491/38589017-93ca3dce-3cdd-11e8-8e98-a27fe09dae36.png)

![screen shot 2018-04-10 at 4 27 07 pm](https://user-images.githubusercontent.com/9169491/38589034-ac2efb8e-3cdd-11e8-969a-d9fd40d38a27.png)

**Comment by SelvarajKaruppusamy** [comment]
@tsoliangwu0130 <.. target="_blank"..> was present in the source code but it was removed by DOMPurify.sanitize() method before rendered in the DOM.

@krv5vignesh We can fix this with the following code,
```DOMPurify.sanitize(msg.response, { SAFE_FOR_JQUERY: true, ALLOWED_ATTR: ["target", "id", "style", "href"] })```

The downside of this approach will be handling new attributes that can added in the future. i,e, On adding new attribute ```ALLOWED_ATTR``` needs to be updated.

But, why do we need to use DOMPurify.sanitize()? Is it okay to remove this?

**Comment by SelvarajKaruppusamy** [comment]
@tsoliangwu0130 @krv5vignesh  I found a [better way](https://github.com/cure53/DOMPurify/blob/master/demos/advanced-config-demo.html) and created a [PR](https://github.com/krv5vignesh/Dictionary-extension/pull/9) with the fix.

**Comment by tsoliangwu0130** [comment]
awesome!

**Comment by krv5vignesh** [comment]
@SelvarajKaruppusamy Thanks. This fix works. DOMPurify is needed because Mozilla once disabled the extension saying assigning data directly to innerHTML is a security risk.

Can you tell me what the difference in the second solution you suggested from the first one? It looks like you removed the "id, style and href" attributes.

**Comment by krv5vignesh** [comment]
@tsoliangwu0130 Thank you for bringing this issue to notice. Woudn't have noticed otherwise.

Update the extension to version 1.5.2. This issue is fixed.

**Comment by SelvarajKaruppusamy** [comment]
@krv5vignesh 
The drawback of the first solution,
If we add more attributes in the future, say label then we also should update **ALLOWED_ATTR** to include "label". 

Where in the second solution we specify DOM.purify() to support "target" attribute via **ADD_ATTR**, so that won't be an issue.
